name: aligndx-prod
services:
  nats:
    image: nats:latest
    command: ["--jetstream"]
    ports:
      - "4222:4222"
    restart: unless-stopped

  ui:
    build:
      context: ../ui  # Adjusted path 
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: ./build/aligndx/Dockerfile
    command: ["tools", "serve", "--http=0.0.0.0:8090"]
    ports:
      - "8090:8090"
    environment:
      ALIGNDX_MQ_URL: "nats://nats:4222"
      ALIGNDX_API_DEFAULTADMINEMAIL: ${API_DEFAULTADMINEMAIL}
      ALIGNDX_API_DEFAULTADMINPASSWORD: ${API_DEFAULTADMINPASSWORD}
      ALIGNDX_API_URL: http://localhost:8090
    restart: unless-stopped
    depends_on:
      - nats
    volumes:
      - ../pb_data:/pb_data  # Adjusted path

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Adjusted path
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - api
      - ui

volumes:
  caddy_data:
  caddy_config:
